name: Bump version and release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Stable Minimal
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Git User Setup
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Conventional Commits
        run: |
          cargo install --locked cocogitto
          cog check --from-latest-tag

      - name: Bump Package Version
        id: versioning
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          cog bump --auto || exit 0
          version=$(git describe --tags "$(git rev-list --tags --max-count=1)")
          echo "version=$version" >> "$GITHUB_OUTPUT"
          sed -ri "s/version = \"(([0-9]+\.)*[0-9]+)\"/version = \"$version\"/" Cargo.toml
          git add Cargo.toml
          git commit --amend --no-edit
          git push origin --tags
          git push origin

      - name: Release
        uses: softprops/action-gh-release@v1
        if: steps.versioning.outputs.version
        with:
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
          tag_name: ${{ steps.versioning.outputs.version }}
          token: ${{ secrets.PAT }}
