on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.versioning.outputs.version }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          depth: 0
      
      - name: Install Stable
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
      
      - name: Git User Setup
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Conventional Commits
        run: |
          cargo install --locked cocogitto
          cog check --from-latest-tag
      
      - name: Versioning
        id: versioning
        run: |
          cog bump --auto || exit 0
          version=$(git describe --tags "$(git rev-list --tags --max-count=1)")
          echo "version=$version" >> "$GITHUB_OUTPUT"
          sed -ire "1,/version/ s/(([0-9]+\.)*[0-9]+)/$version/" Cargo.toml
          git add Cargo.toml && git commit --amend --no-edit
          
      - name: Git Push
        run: |
          git push origin --tags
          git push origin
      
      - name: Tag Version
        run: |
          echo "Released Tag: ${{ steps.prerelease.outputs.version }}"
